In [3]:
import numpy as np

In [2]:
matrix = np.array([
        [5,5,84,3,9],
        [6,11,1,55,58],
        [1,20,48,12,36],
        [8,4,41,93,98],
        [6,17,64,0,13]
    ])

In [5]:
def task1(matrix):
    i,j= np.shape(matrix)
    for k in range(i):
        for l in range(j):
            if k>l:
                matrix[k][l]=0
    
    upper=np.triu(matrix)
    return np.transpose(upper)
print(task1(matrix))

[[ 5  0  0  0  0]
 [ 5 11  0  0  0]
 [84  1 48  0  0]
 [ 3 55 12 93  0]
 [ 9 58 36 98 13]]


In [12]:
def task2(matrix):
    '''return mean, median, std (precision 2), all along x, determinant, inverse, pseudo-inverse'''
    mean = np.mean(matrix,axis=0)
    median = np.median(matrix,axis=0,overwrite_input=False,keepdims=False,out=None)
    std = np.std(matrix,axis=0)
    det = np.linalg.det(matrix)
    if(det!=0):
        inv=np.linalg.inv(matrix)
    else:
        inv=None
    pseudoinv=np.linalg.pinv(matrix)

    return mean, median, std, det, inv, pseudoinv

mean, median, std, det, inv, pseudoinv = task2(matrix)
print("Mean: ", mean)
print("Median: ", median)
print("Standard Deviation: ", np.around(std, decimals = 2))
print("Determinant: ", np.around(det,decimals = 2))
if det != 0:
    print("Inverse: ", np.around(inv,decimals=2))
else:
    print("Pseudo-Inverse: ", np.around(pseudoinv, decimals=2))

Mean:  [ 1.   3.2 26.6 32.6 42.8]
Median:  [ 0.  0.  1. 12. 36.]
Standard Deviation:  [ 2.    4.35 34.13 36.09 32.73]
Determinant:  3191760.0
Inverse:  [[ 0.2  -0.09 -0.35  0.09  0.54]
 [ 0.    0.09 -0.   -0.05  0.  ]
 [ 0.    0.    0.02 -0.   -0.04]
 [ 0.    0.    0.    0.01 -0.08]
 [ 0.    0.    0.    0.    0.08]]


In [7]:
def task3(matrix, num = 0, padding = 3):
    padded=np.pad(matrix,pad_width=padding,mode='constant',constant_values=num)
    return padded

print(task3(matrix))

[[ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  5  5 84  3  9  0  0  0]
 [ 0  0  0  0 11  1 55 58  0  0  0]
 [ 0  0  0  0  0 48 12 36  0  0  0]
 [ 0  0  0  0  0  0 93 98  0  0  0]
 [ 0  0  0  0  0  0  0 13  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]]
